// <auto-generated />
using EventManagement.Registration.Data;
using EventManagement.Registration.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EventManagement.Registration.Data.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    partial class RegistrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventManagement.Registration.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalInfo");

                    b.Property<DateTime>("End");

                    b.Property<int>("EventId");

                    b.Property<string>("EventName");

                    b.Property<string>("LecturerName");

                    b.Property<string>("Location");

                    b.Property<double>("Price");

                    b.Property<string>("ResourceName");

                    b.Property<int>("ResourcePlacesCount");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventManagement.Registration.Data.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventId");

                    b.Property<Guid>("PaymentId");

                    b.Property<int>("PaymentStatus");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EventManagement.Registration.Data.Models.Registration", b =>
                {
                    b.HasOne("EventManagement.Registration.Data.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId");
                });
#pragma warning restore 612, 618
        }
    }
}
