// <auto-generated />
using EventManagement.Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EventManagement.Portal.Data.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.PortalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsAdmin");

                    b.Property<int?>("LanguageId");

                    b.Property<string>("Link")
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("PortalLinks");
                });

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.UserDateTimeFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("UserDateTimeFormats");
                });

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.UserLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DateTimeFormatId");

                    b.Property<int>("LanguageId");

                    b.Property<string>("UserName")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("DateTimeFormatId");

                    b.HasIndex("LanguageId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.PortalLink", b =>
                {
                    b.HasOne("KPMG.TaxRay.Portal.Core.Entities.UserLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");
                });

            modelBuilder.Entity("KPMG.TaxRay.Portal.Core.Entities.UserSetting", b =>
                {
                    b.HasOne("KPMG.TaxRay.Portal.Core.Entities.UserDateTimeFormat", "DateTimeFormat")
                        .WithMany()
                        .HasForeignKey("DateTimeFormatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KPMG.TaxRay.Portal.Core.Entities.UserLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
